# Generated by Django 6.0.2 on 2026-02-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Designates whether the profile is private.'),
        ),
    ]
