# Generated by Django 6.0.2 on 2026-02-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If true, only followers can see content.'),
        ),
    ]
