# Generated by Django 6.0.2 on 2026-02-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
